function Hd = teste
%TESTE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 29-Oct-2024 00:07:56

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 312.5;  % Sampling Frequency

N    = 64;       % Order
Fc   = 90;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
